#!/usr/bin/env python
"""Generate the Eq. 35 constant correction for lens_only + analytic_marg mode.

Produces dr6plus_lenslike/data/v1.0/lens_only_const.npy, consumed by
load_data(analytic_marg=True) and applied in get_lens_only_corrected_clkk():

    nclkk = clkk + dN1_kk @ clkk + eq35_const

with (all in C_L^{kappa kappa} units, L = 0 .. 4000; N1 terms L = 0 .. 2999)

    eq35_const = norm_term + n1_cmb_term + n1_kk_term
    norm_term  = [ sum_X -2 (dAL/dC^X @ dCl^X) / fAL ] * clkk_fid
    n1_cmb_term = sum_X dN1/dC^X @ dCl^X
    n1_kk_term  = - dN1/dC^kk @ clkk_fid

for X in {TT, EE, TE} (BB is not measured by the ACT DR6 CMB-only 2pt data
and is skipped). This is Eq. (35) of the DR6 lensing paper (Planck 2018
lensing Sec. 3.2.1), with C-hat taken to be the foreground-marginalized ACT
DR6 CMB-only bandpowers, the same dataset whose bandpower covariance enters
the Eq. (34) covariance (covmat_act_cmbmarg_analytic.txt, generated by
src/lensing_only_cov_marginalization.py).

Delta-Cl construction (the 2026-08-31 fix): the measured bandpowers are
compared to the WINDOW-BINNED fiducial, not to the fiducial evaluated at the
bin-center ell tag. The bandpower difference

    dD_b = D_b^data - sum_ell W_{b,ell} D_ell^fid

is converted to C_ell at the bin-center ell and linearly interpolated onto
ell in [600, 3000] (zero outside: the DR6 reconstruction uses 600 < ell <
3000 only). Evaluating the fiducial at the tag ell instead leaves a coherent
binning residual that the normalization response amplifies to a -19% theory
shift at L = 100; the window-binned construction gives -1.0%.

Run with the cluster module environment loaded (see repo README).
"""
import os
import datetime
import numpy as np
import sacc

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "dr6plus_lenslike", "data", "v1.0")
DATA_DIR = os.path.normpath(DATA_DIR)
LIKE_CORRS = os.path.join(DATA_DIR, "like_corrs")
# Public ACT DR6 CMB-only release v1.0 (see src/lensing_only_cov_marginalization.py); until 2026-09-25
# the DR6-ACT-lite repository file act_dr6_cmb_sacc.fits, a different data version.
ACT_SACC_FILE = "/scratch/jiaqu/likelihood_data/data/ACTDR6CMBonly/v1.0/dr6_data_cmbonly.fits"
OUT_FILE = os.path.join(DATA_DIR, "lens_only_const.npy")

ELL_MIN, ELL_MAX = 600, 3000
SACC_TYPES = {"TT": "cl_00", "TE": "cl_0e", "EE": "cl_ee"}
DAL_INDEX = {"TT": 0, "EE": 1, "TE": 3}   # dAL/dC index order [TT, EE, BB, TE]


def build_delta_Cl(s, fid_ells, fid_Dl):
    """Per-ell Delta_Cl over [ELL_MIN, ELL_MAX] from window-binned residuals."""
    ell_range = np.arange(ELL_MIN, ELL_MAX + 1)
    delta_Cl = {}
    for name, t in SACC_TYPES.items():
        idx = np.array(s.indices(t))
        ells = np.array([s.data[i].get_tag("ell") for i in idx])
        vals = np.array([s.data[i].value for i in idx])          # D_ell, muK^2
        srt = np.argsort(ells)
        ells, vals, idx = ells[srt], vals[srt], idx[srt]
        keep = ells >= ELL_MIN
        ells, vals, idx = ells[keep], vals[keep], idx[keep]

        win = s.get_bandpower_windows(list(idx))
        W = win.weight.T                                          # (nbin, nell)
        wl = win.values.astype(int)
        dense = np.zeros(wl.max() + 1)
        m = fid_ells <= wl.max()
        dense[fid_ells[m]] = fid_Dl[name][m]
        fid_binned = W @ dense[wl]

        dDl_bp = vals - fid_binned                                # binned D_ell residual
        dCl_bp = dDl_bp * 2 * np.pi / (ells * (ells + 1))
        delta_Cl[name] = np.interp(ell_range, ells, dCl_bp, left=0.0, right=0.0)
    return ell_range, delta_Cl


def main():
    # Fiducial spectra (cosmo2017, the normalization/N1 fiducial)
    fid = np.loadtxt(f"{LIKE_CORRS}/cosmo2017_10K_acc3_lensedCls.dat")
    fid_ells = fid[:, 0].astype(int)
    fid_Dl = {"TT": fid[:, 1], "EE": fid[:, 2], "TE": fid[:, 4]}

    lp = np.loadtxt(f"{LIKE_CORRS}/cosmo2017_10K_acc3_lenspotentialCls.dat")
    clkk_fid = np.zeros(int(lp[-1, 0]) + 1)          # index by L: the file starts at L = 2
    clkk_fid[lp[:, 0].astype(int)] = lp[:, 5] * 2 * np.pi / 4
    clkk_fid_trunc = clkk_fid[:4001]

    fAL = np.loadtxt(f"{LIKE_CORRS}/n0mv_fiducial_lmin600_lmax3000_Lmin0_Lmax4000.txt")[1]
    dAL_dC = np.load(f"{LIKE_CORRS}/norm_correction_matrix_Lmin0_Lmax4000.npy")

    s = sacc.Sacc.load_fits(ACT_SACC_FILE)
    ell_range, delta_Cl = build_delta_Cl(s, fid_ells, fid_Dl)

    # Full-length Delta_Cl arrays, index order [TT, EE, BB, TE]
    delta_full = np.zeros((4, 3001))
    for name in SACC_TYPES:
        delta_full[DAL_INDEX[name], ELL_MIN:ELL_MAX + 1] = delta_Cl[name]

    # Term 1: normalization
    norm_corr = np.zeros(4001)
    for name in SACC_TYPES:
        raw = dAL_dC[DAL_INDEX[name]] @ delta_full[DAL_INDEX[name]]
        norm_corr[2:] += -2 * raw[2:] / fAL[2:]
    norm_term = norm_corr * clkk_fid_trunc

    # Term 2: N1 response to the measured CMB offset
    n1_cmb_term = np.zeros(3000)
    for name in SACC_TYPES:
        dN1 = np.loadtxt(f"{LIKE_CORRS}/N1der_{name}_lmin600_lmax3000_full.txt")
        n1_cmb_term += dN1 @ delta_full[DAL_INDEX[name]][:dN1.shape[1]]

    # Term 3: -dN1/dC^kk @ clkk_fid (independent of the measured CMB)
    dN1_KK = np.loadtxt(f"{LIKE_CORRS}/N1der_KK_lmin600_lmax3000_full.txt")
    n1_kk_term = -(dN1_KK @ clkk_fid[:dN1_KK.shape[1]])

    eq35_const = norm_term.copy()
    eq35_const[:3000] += n1_cmb_term + n1_kk_term

    out = {
        "L": np.arange(len(eq35_const)),
        "eq35_const": eq35_const,
        "norm_term": norm_term,
        "n1_cmb_term": n1_cmb_term,
        "n1_kk_term": n1_kk_term,
        "clkk_fid": clkk_fid_trunc,
        "source_cmb_data": "ACT DR6 CMB-only (foreground-marginalized), ell >= 600",
        "sacc_file": ACT_SACC_FILE,
        "clkk_fid_indexing": "by L (file starts at L = 2)",
        "delta_cl_method": "data bandpower minus window-binned fiducial, "
                           "interpolated to ell in [600, 3000]",
        "date_generated": datetime.datetime.now().isoformat(),
        "generator": "src/generate_lens_only_const.py",
    }
    np.save(OUT_FILE, out)
    print(f"Saved {OUT_FILE}")

    for L in (100, 500, 1000):
        print(f"L={L}: norm={100*norm_term[L]/clkk_fid[L]:+.3f}%  "
              f"N1_cmb={100*n1_cmb_term[L]/clkk_fid[L]:+.3f}%  "
              f"N1_kk={100*n1_kk_term[L]/clkk_fid[L]:+.3f}%  "
              f"net(norm+N1cmb)={100*(norm_term[L]+n1_cmb_term[L])/clkk_fid[L]:+.3f}%")


if __name__ == "__main__":
    main()
